language: cpp
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - nvidia-cuda-toolkit


# install build tools
before_install:
  - wget https://services.gradle.org/distributions/gradle-5.0-bin.zip
  - unzip -d $HOME gradle-5.0-bin.zip
  # probably don't need this but just to be sure
  - rm -rf gradle-5.0-bin.zip
  # add gradle bin to path at the beginning to ensure it overwrites old gradle
  - export PATH="$HOME/gradle-5.0/bin:$PATH"
  - gem install mdl
  - git clone --depth=1 --branch=master https://github.com/Michionlion/optix.git $HOME/optix
  - tree /opt/cuda

# install dependencies
install:
  - gradle deps --console=plain

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/5.0
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/modules-2
    - $HOME/optix

script:
  # build
  - gradle clean --console=plain -Poptix_location=$HOME/optix
  # lint
  - gradle assemble --console=plain -Poptix_location=$HOME/optix
  - gradle lint --console=plain -Poptix_location=$HOME/optix
